package collegedetails;


import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class CollegeDetails extends javax.swing.JFrame {

    private String gender;
    
    /**
     * Creates new form Details
     */
    public CollegeDetails() {
        initComponents();
        show_user();
    }
    public ArrayList<User> userlist()
    {
       ArrayList<User> userlist = new ArrayList<>();
    try{
      Class.forName("com.mysql.jdbc.Driver");
      Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/studentrecords","root","Krishna@1802");    
      String query1 = "SELECT * FROM studentrec";
      Statement st = con.createStatement();
      ResultSet rs = st.executeQuery(query1);
      User user;
      //System.out.println(rs.getString("subject"));
      while(rs.next()){
          user = new User(rs.getString("name"),rs.getString("address"),rs.getString("gender"),rs.getString("knowledge"),rs.getString("subject"));
          userlist.add(user);
      }
     }
    catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
    }
    return userlist;
    }
    public void show_user(){
        ArrayList<User> list = userlist();
        DefaultTableModel model = (DefaultTableModel)jTable_Display_user.getModel();
        Object[] row = new Object[5];
        for(int i=0;i<list.size();i++)
        {
            row[0] = list.get(i).getname();
            row[1] = list.get(i).getaddress();
            row[2] = list.get(i).getgender();
            row[3] = list.get(i).getknowledge();
            row[4] = list.get(i).getsubject();
            model.addRow(row);
        }
    }
    public void updatetable(String name,String address,String gender,String knowledge,String course){
        DefaultTableModel model = (DefaultTableModel)jTable_Display_user.getModel();
        Object[] row = new Object[5];
        row[0] = name;
        row[1] = address;
        row[2] = gender;
        row[3] = knowledge;
        row[4] = course;
        model.addRow(row);
    }
    public void resetaction()
    {
        nametext.setText("");
        addtext.setText("");
        buttonGroup1.clearSelection();
        buttonGroup2.clearSelection();
        subjectcombo.setSelectedItem("Click to Choose...");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        addtext = new javax.swing.JTextField();
        nametext = new javax.swing.JTextField();
        maleradio = new javax.swing.JRadioButton();
        femaleradio = new javax.swing.JRadioButton();
        pythonradio = new javax.swing.JRadioButton();
        javaradio = new javax.swing.JRadioButton();
        subjectcombo = new javax.swing.JComboBox<>();
        resetbutton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Display_user = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        othersradio = new javax.swing.JRadioButton();
        cppradio = new javax.swing.JRadioButton();
        deletebtn = new javax.swing.JButton();
        savebutton = new javax.swing.JButton();
        previewbtn = new javax.swing.JButton();
        updatebtn = new javax.swing.JButton();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student Skill Records");
        setBackground(new java.awt.Color(102, 255, 204));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Product Sans", 0, 14)); // NOI18N
        jLabel1.setText("Subject");

        jLabel2.setFont(new java.awt.Font("Product Sans", 0, 14)); // NOI18N
        jLabel2.setText("Name");

        jLabel3.setFont(new java.awt.Font("Product Sans", 0, 14)); // NOI18N
        jLabel3.setText("Address");

        jLabel4.setFont(new java.awt.Font("Product Sans", 0, 14)); // NOI18N
        jLabel4.setText("Gender");

        jLabel5.setFont(new java.awt.Font("Product Sans", 0, 14)); // NOI18N
        jLabel5.setText("Knowledge");

        addtext.setFont(new java.awt.Font("Product Sans", 0, 12)); // NOI18N
        addtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addtextActionPerformed(evt);
            }
        });

        nametext.setFont(new java.awt.Font("Product Sans", 0, 12)); // NOI18N
        nametext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nametextActionPerformed(evt);
            }
        });

        buttonGroup1.add(maleradio);
        maleradio.setFont(new java.awt.Font("Product Sans", 0, 14)); // NOI18N
        maleradio.setText("Male");

        buttonGroup1.add(femaleradio);
        femaleradio.setFont(new java.awt.Font("Product Sans", 0, 14)); // NOI18N
        femaleradio.setText("Female");
        femaleradio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleradioActionPerformed(evt);
            }
        });

        buttonGroup2.add(pythonradio);
        pythonradio.setFont(new java.awt.Font("Product Sans", 0, 14)); // NOI18N
        pythonradio.setText("Python");
        pythonradio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pythonradioActionPerformed(evt);
            }
        });

        buttonGroup2.add(javaradio);
        javaradio.setFont(new java.awt.Font("Product Sans", 0, 14)); // NOI18N
        javaradio.setText("Java");
        javaradio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                javaradioActionPerformed(evt);
            }
        });

        subjectcombo.setFont(new java.awt.Font("Product Sans", 0, 14)); // NOI18N
        subjectcombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Click to Choose...", "Computer Science", "Chemistry", "Electrical Engineering" }));
        subjectcombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subjectcomboActionPerformed(evt);
            }
        });

        resetbutton.setFont(new java.awt.Font("Product Sans", 0, 14)); // NOI18N
        resetbutton.setText("Reset");
        resetbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetbuttonActionPerformed(evt);
            }
        });

        jTable_Display_user.setFont(new java.awt.Font("Product Sans", 0, 12)); // NOI18N
        jTable_Display_user.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Address", "Gender", "Knowledge", "Subject"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable_Display_user);
        if (jTable_Display_user.getColumnModel().getColumnCount() > 0) {
            jTable_Display_user.getColumnModel().getColumn(0).setResizable(false);
            jTable_Display_user.getColumnModel().getColumn(1).setResizable(false);
            jTable_Display_user.getColumnModel().getColumn(2).setResizable(false);
            jTable_Display_user.getColumnModel().getColumn(3).setResizable(false);
            jTable_Display_user.getColumnModel().getColumn(4).setResizable(false);
        }

        jLabel6.setFont(new java.awt.Font("Product Sans", 0, 24)); // NOI18N
        jLabel6.setText("Student Details");

        buttonGroup1.add(othersradio);
        othersradio.setFont(new java.awt.Font("Product Sans", 0, 14)); // NOI18N
        othersradio.setText("Others");
        othersradio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                othersradioActionPerformed(evt);
            }
        });

        buttonGroup2.add(cppradio);
        cppradio.setFont(new java.awt.Font("Product Sans", 0, 14)); // NOI18N
        cppradio.setText("C/C++");
        cppradio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cppradioActionPerformed(evt);
            }
        });

        deletebtn.setFont(new java.awt.Font("Product Sans", 0, 14)); // NOI18N
        deletebtn.setText("Delete");
        deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebtnActionPerformed(evt);
            }
        });

        savebutton.setFont(new java.awt.Font("Product Sans", 0, 14)); // NOI18N
        savebutton.setText("Add Student");
        savebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebuttonActionPerformed(evt);
            }
        });

        previewbtn.setFont(new java.awt.Font("Product Sans", 0, 14)); // NOI18N
        previewbtn.setText("Preview Details");
        previewbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previewbtnActionPerformed(evt);
            }
        });

        updatebtn.setFont(new java.awt.Font("Product Sans", 1, 14)); // NOI18N
        updatebtn.setText("Update Details");
        updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(102, 102, 102)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(14, 14, 14)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(subjectcombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(addtext, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                            .addComponent(nametext)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(maleradio)
                                                    .addComponent(javaradio))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(pythonradio)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(cppradio))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(femaleradio)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 5, Short.MAX_VALUE)
                                                        .addComponent(othersradio))))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(savebutton, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                                            .addComponent(deletebtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(103, 103, 103)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(resetbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(previewbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(updatebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(130, 130, 130)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nametext, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addtext, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(maleradio)
                            .addComponent(femaleradio)
                            .addComponent(othersradio))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pythonradio)
                            .addComponent(javaradio)
                            .addComponent(cppradio))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(subjectcombo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(resetbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(savebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(deletebtn, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                            .addComponent(previewbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(updatebtn, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addtextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addtextActionPerformed

    private void nametextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nametextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nametextActionPerformed

    private void pythonradioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pythonradioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pythonradioActionPerformed

    private void javaradioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_javaradioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_javaradioActionPerformed

    private void femaleradioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleradioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_femaleradioActionPerformed

    private void othersradioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_othersradioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_othersradioActionPerformed

    private void resetbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetbuttonActionPerformed
      resetaction();  // TODO add your handling code here:
    }//GEN-LAST:event_resetbuttonActionPerformed

    private void cppradioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cppradioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cppradioActionPerformed

    private void subjectcomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subjectcomboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subjectcomboActionPerformed

    private void savebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebuttonActionPerformed
    try{
      Class.forName("com.mysql.jdbc.Driver");
      Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/studentrecords","root","Krishna@1802");    
      String query = "insert into studentrec(name, address, gender, knowledge, subject)values(?,?,?,?,?)";
      PreparedStatement pst = con.prepareStatement(query);
      pst.setString(1, nametext.getText());
      pst.setString(2, addtext.getText());
      String name = nametext.getText();
      String address = addtext.getText();
      if(maleradio.isSelected())
      {
          gender = "Male";
      }
      if(femaleradio.isSelected())
      {
          gender = "Female";
      }
      if(othersradio.isSelected()){
                gender="Others";
      }
      pst.setString(3,gender);
      String knowledge = "";
      if(javaradio.isSelected())
      {
          knowledge += javaradio.getText()+"";
      }
      if(pythonradio.isSelected())
      {
          knowledge += pythonradio.getText()+"";
      }
      if(cppradio.isSelected())
      {
          knowledge+=cppradio.getText()+" ";
      }
      pst.setString(4, knowledge);
      String course;
      course = subjectcombo.getSelectedItem().toString();
      pst.setString(5,course);
      pst.executeUpdate();
      JOptionPane.showMessageDialog(null, "Inserted Sucessfully!");
      updatetable(name,address,gender,knowledge,course);
      resetaction();
    }
    
     catch(Exception e){
      JOptionPane.showMessageDialog(null, e);
        }
                                    
    }//GEN-LAST:event_savebuttonActionPerformed

    private void deletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebtnActionPerformed
        // TODO add your handling code here:
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/studentrecords","root","Krishna@1802");    
            int row = jTable_Display_user.getSelectedRow();
            String value=(jTable_Display_user.getModel().getValueAt(row, 0).toString());
            String query="DELETE FROM studentrec where name=\""+value+"\"";
            PreparedStatement pst = con.prepareStatement(query);
            pst.executeUpdate();
            DefaultTableModel model = (DefaultTableModel)jTable_Display_user.getModel();
            model.setRowCount(0);
            show_user();
            JOptionPane.showMessageDialog(null,"Deleted Successfully!");
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
 
    }//GEN-LAST:event_deletebtnActionPerformed

    private void previewbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previewbtnActionPerformed
        // TODO add your handling code here
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/studentrecords","root","Krishna@1802");    
            int row= jTable_Display_user.getSelectedRow();
            String value_name=(jTable_Display_user.getModel().getValueAt(row,0).toString());  
            String value_address = (jTable_Display_user.getModel().getValueAt(row,1).toString());
            String value_gender = (jTable_Display_user.getModel().getValueAt(row, 2).toString());
            String value_knowledge = (jTable_Display_user.getModel().getValueAt(row, 3).toString());
            String value_subject = (jTable_Display_user.getModel().getValueAt(row, 4).toString());
            nametext.setText(value_name);
            addtext.setText(value_address);
            if("Male".equals(value_gender))
            {
               maleradio.setSelected(true);
            }
            if("Female".equals(value_gender))
            {
                femaleradio.setSelected(true);
            }
            if("Others".equals(value_gender))
            {
                othersradio.setSelected(true);
            }
            if("Java".equals(value_knowledge))
            {
                javaradio.setSelected(true);
            }
            if("Python".equals(value_knowledge))
            {
                pythonradio.setSelected(true);
            }
            if("C/C++".equals(value_knowledge))
            {
                cppradio.setSelected(true);
            }
            subjectcombo.setSelectedItem(value_subject);
        }
         catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }                             
    }//GEN-LAST:event_previewbtnActionPerformed

    private void updatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebtnActionPerformed
        // TODO add your handling code here:
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/studentrecords","root","Krishna@1802");    
            int row= jTable_Display_user.getSelectedRow();
            String value=(jTable_Display_user.getModel().getValueAt(row, 0).toString());
            String query = "UPDATE studentrec SET name=?, address=?, gender=?, knowledge=?,  subject=? where name=\""+value+"\"";
            PreparedStatement pst = con.prepareStatement(query);
            pst.setString(1, nametext.getText());
            pst.setString(2, addtext.getText());
            if(maleradio.isSelected()){
                pst.setString(3, "Male");
            }
            if(femaleradio.isSelected()){
                pst.setString(3, "Female");
            }
            if(othersradio.isSelected()){
                pst.setString(3, "Others");
            }
            if(javaradio.isSelected())
            {
                pst.setString(4, "Java");
            }
            if(pythonradio.isSelected())
            {
                pst.setString(4, "Python");
            }
            if(cppradio.isSelected())
            {
                pst.setString(4, "C/C++");
            }
            String course;
            course=subjectcombo.getSelectedItem().toString();
            pst.setString(5, course);
            pst.executeUpdate();
            DefaultTableModel model = (DefaultTableModel)jTable_Display_user.getModel();
            model.setRowCount(0);
            show_user();
            JOptionPane.showMessageDialog(null, "Updated Sucessfully!");
        }
         catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }                                        
    }//GEN-LAST:event_updatebtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CollegeDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CollegeDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CollegeDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CollegeDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CollegeDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addtext;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JRadioButton cppradio;
    private javax.swing.JButton deletebtn;
    private javax.swing.JRadioButton femaleradio;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Display_user;
    private javax.swing.JRadioButton javaradio;
    private javax.swing.JRadioButton maleradio;
    private javax.swing.JTextField nametext;
    private javax.swing.JRadioButton othersradio;
    private javax.swing.JButton previewbtn;
    private javax.swing.JRadioButton pythonradio;
    private javax.swing.JButton resetbutton;
    private javax.swing.JButton savebutton;
    private javax.swing.JComboBox<String> subjectcombo;
    private javax.swing.JButton updatebtn;
    // End of variables declaration//GEN-END:variables
}
